// Generated by CoffeeScript 1.8.0
(function() {
  var DS, SDS, assert, data, expect, should, sinon, stormify;

  stormify = require('../lib/stormify');

  DS = stormify.DS;

  assert = require('chai').assert;

  should = require('chai').should;

  expect = require('chai').expect;

  sinon = require('sinon');

  SDS = stormify.createStore({
    store: require('./stores/test-store')
  });

  data = {
    id: 501,
    street: "O.M.R",
    city: "chennai",
    phoneno: 100
  };

  describe('DS.Model unit test cases ', function() {
    return it('Basic DSModel object creation test', function() {
      var TestModel, result;
      TestModel = SDS.createRecord('address', data);
      assert.isDefined(TestModel);
      expect(TestModel.id).to.equal(data.id);
      expect(TestModel.properties.id.value).to.equal(data.id);
      expect(TestModel.properties.street.value).to.equal(data.street);
      expect(TestModel.properties.city.value).to.equal(data.city);
      expect(TestModel.properties.phoneno.value).to.equal(data.phoneno);
      TestModel = null;
      TestModel = SDS.findRecord('address', data.id);
      assert.isDefined(TestModel);
      expect(TestModel.id).to.equal(data.id);
      expect(TestModel.properties.id.value).to.equal(data.id);
      expect(TestModel.properties.street.value).to.equal(data.street);
      expect(TestModel.properties.city.value).to.equal(data.city);
      expect(TestModel.properties.phoneno.value).to.equal(data.phoneno);
      TestModel = null;
      result = SDS.findBy('address', {
        city: "chennai"
      });
      return console.log(result);
    });
  });

}).call(this);
