// Generated by CoffeeScript 1.8.0
(function() {
  var DS, TestModel, stormify,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  stormify = require('../../lib/stormify');

  DS = stormify.DS;

  TestModel = (function(_super) {
    __extends(TestModel, _super);

    function TestModel() {
      return TestModel.__super__.constructor.apply(this, arguments);
    }

    TestModel.prototype.name = 'address';

    TestModel.prototype.schema = {
      id: DS.attr('string', {
        required: false
      }),
      street: DS.attr('string', {
        required: true
      }),
      city: DS.attr('string', {
        required: true
      }),
      phoneno: DS.attr('number', {
        required: true
      }),
      date: DS.attr('date', {
        required: false
      })
    };

    return TestModel;

  })(DS.Model);

  module.exports = TestModel;

}).call(this);
