// Generated by CoffeeScript 1.8.0
(function() {
  var DS, YangStorm,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  DS = require('./data-storm');

  YangStorm = (function(_super) {
    var needle;

    __extends(YangStorm, _super);

    YangStorm.Generator = require('./yang/yang-generator');

    function YangStorm() {
      this.generator = new YangStorm.Generator;
      YangStorm.__super__.constructor.apply(this, arguments);
    }

    needle = require('needle');

    YangStorm.prototype["import"] = function(yang) {
      this.assert((yang != null) && typeof yang === 'string', 'cannot import without valid YANG text input');
      if (/\b((?=[a-z0-9-]{1,63}\.)(xn--)?[a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,63}\b/.test(yang)) {
        return needle.get(yang, function(err, res) {
          var module;
          try {
            module = this.generator.generate(res.body);
          } catch (_error) {
            err = _error;
            console.log(err);
          }
          return module;
        });
      }
    };

    return YangStorm;

  })(DS);

  module.exports = YangStorm;

}).call(this);
